version: '3.8'
services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    networks:
      - default
  pgsync:
    build:
      context: ../pgsync
      dockerfile: ../pgsync/Dockerfile
    command: ./entrypoint.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "app"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - redis
      - elasticsearch
    environment:
      - PG_USER=${PG_USERNAME}
      - PG_HOST=postgres
      - PG_PASSWORD=${PG_PASSWORD}
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - REDIS_AUTH=${REDIS_PASSWORD}
    networks:
      - postgres_default
      - default

networks:
  default:
    driver: bridge
  postgres_default:
    external: true
